# Generated by Django 4.2.7 on 2023-11-29 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert')], default='breakfast', max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='recipe_images/')),
                ('cooking_duration', models.IntegerField(default=15, help_text='Duration in minutes')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('moderate', 'Moderate'), ('difficult', 'Difficult'), ('very_difficult', 'Very Difficult')], max_length=15)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='djangodazzle.recipe')),
            ],
        ),
    ]
