# Generated by Django 4.2.7 on 2023-11-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangodazzle', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='user_images/'),
        ),
    ]
