# Generated by Django 4.2.7 on 2023-12-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangodazzle', '0004_recipe_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='creator',
        ),
    ]
