# Generated by Django 4.2.7 on 2023-12-02 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangodazzle', '0006_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='djangodazzle.userprofile'),
        ),
    ]
