# Generated by Django 4.2.7 on 2023-12-02 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangodazzle', '0007_recipe_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user_profile',
        ),
    ]
